---
user_variants:
  test:
    env_override: {}
    env_extension: {}
default_variants:
- debug
- release
platforms:
- OS: 
  ARCH: 
  config: "/config"
- OS: 
  ARCH: 
  config: "/config"
automatic_module_discovery:
  enable: false
  scan_depth: 7
  skip_patterns:
  - ".no_recurse"
modules_list:
- driver
- driver2
- app
- example
