Import('*')
"""
SconsMinimumRequiredVersion("x.x.x")

FindLibrary("module::lib", 'REQUIRED')
FindLibrary("module::lib", 'OPTIONAL')

Set("DENIFE_NAME_WHICH_WILL_PRESENT_DURING_BUILD", "define_value")
"""
prog_name = "printer"
prog_version = "0.1"

sources = \
[
	"main.c"
]

CreateDefaultTargetExecutable(
	name=prog_name,
	version=prog_version,
	sources=sources,
	libs=['driver::driver', 'driver2::driver2' ])
