Import('*')
"""
SconsMinimumRequiredVersion("x.x.x")

FindLibrary("module::lib", REQUIRED)
FindLibrary("module::lib", OPTIONAL)

Set("DENIFE_NAME_WHICH_WILL_PRESENT_DURING_BUILD", "define_value")
"""
lib_name = "driver"
module_version = "0.1"

public_headers = \
[
	"include/driver/driver.h"
]

sources = \
[
	"src/driver.c"
]

CreateDefaultTargetLib(
	name=lib_name,
	version=module_version,
	sources=sources,
	headers=public_headers)
